#!/usr/bin/env bash
set -euo pipefail

# Elastic Cloud（または任意の ES）接続情報を保存し、Secret Manager / Cloud Build トリガーへ反映する。
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CREDS_FILE="$ROOT/infra/elasticsearch/.credentials"
ENV_FILE="$ROOT/services/backend-api/.env"

PROJECT="${GOOGLE_CLOUD_PROJECT:-$(gcloud config get-value project 2>/dev/null || true)}"
if [[ -z "$PROJECT" || "$PROJECT" == "(unset)" ]]; then
  echo "GOOGLE_CLOUD_PROJECT または gcloud config set project を設定してください" >&2
  exit 1
fi

REGION="${GOOGLE_CLOUD_LOCATION:-asia-northeast1}"

is_local_es_node() {
  local node="${1:-}"
  [[ "$node" == *localhost* || "$node" == *127.0.0.1* ]]
}

# 本番セットアップでは .credentials を優先。backend-api/.env の localhost ES_NODE は使わない。
if [[ -f "$CREDS_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$CREDS_FILE"
  set +a
fi

if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  source "$ENV_FILE"
  set +a
  if is_local_es_node "${ES_NODE:-}"; then
    unset ES_NODE
  fi
fi

echo "=== Elasticsearch 本番セットアップ ==="
echo "Project: ${PROJECT}"
echo ""
echo "Elastic Cloud の場合:"
echo "  1. https://cloud.elastic.co → Deployments → 東京 (asia-northeast1) 推奨"
echo "  2. Elasticsearch endpoint を ES_NODE に設定"
echo "  3. Security → API keys で ES_API_KEY を作成（推奨）"
echo ""

if [[ -n "${ES_NODE:-}" ]] && ! is_local_es_node "$ES_NODE"; then
  echo "現在の ES_NODE: ${ES_NODE}"
  read -r -p "この URL を使いますか？ [Y/n]: " USE_CURRENT
  if [[ "${USE_CURRENT:-Y}" =~ ^[Nn] ]]; then
    ES_NODE=""
  fi
fi

if [[ -z "${ES_NODE:-}" ]]; then
  read -r -p "ES_NODE (例: https://xxx.es.asia-northeast1.gcp.cloud.es.io:443): " ES_NODE
fi
if [[ -z "$ES_NODE" ]]; then
  echo "ES_NODE は必須です。" >&2
  exit 1
fi
if is_local_es_node "$ES_NODE"; then
  echo "ES_NODE に localhost は指定できません。Elastic Cloud の endpoint URL を入力してください。" >&2
  exit 1
fi

if [[ -z "${ES_API_KEY:-}" && -z "${ES_PASSWORD:-}" ]]; then
  echo ""
  echo "認証: API キー（推奨）または Basic 認証のどちらかを設定してください。"
  read -r -p "ES_API_KEY (空ならスキップ): " ES_API_KEY
  if [[ -z "$ES_API_KEY" ]]; then
    read -r -p "ES_USERNAME [elastic]: " ES_USERNAME
    ES_USERNAME="${ES_USERNAME:-elastic}"
    read -r -s -p "ES_PASSWORD: " ES_PASSWORD
    echo ""
  fi
fi

ES_INDEX="${ES_INDEX:-spots}"
ES_VECTOR_DIMS="${ES_VECTOR_DIMS:-1536}"

mkdir -p "$(dirname "$CREDS_FILE")"
cat >"$CREDS_FILE" <<EOF
# Generated by infra/elasticsearch/setup.sh — DO NOT COMMIT
PROJECT=${PROJECT}
ES_NODE=${ES_NODE}
ES_INDEX=${ES_INDEX}
ES_VECTOR_DIMS=${ES_VECTOR_DIMS}
EOF
if [[ -n "${ES_API_KEY:-}" ]]; then
  echo "ES_API_KEY=${ES_API_KEY}" >>"$CREDS_FILE"
fi
if [[ -n "${ES_USERNAME:-}" ]]; then
  echo "ES_USERNAME=${ES_USERNAME}" >>"$CREDS_FILE"
fi
if [[ -n "${ES_PASSWORD:-}" ]]; then
  echo "ES_PASSWORD=${ES_PASSWORD}" >>"$CREDS_FILE"
fi
chmod 600 "$CREDS_FILE"

echo ""
echo "Credentials saved to: infra/elasticsearch/.credentials"
echo "  ES_NODE=${ES_NODE}"
if [[ -n "${ES_API_KEY:-}" ]]; then
  echo "  ES_API_KEY=(設定済み)"
elif [[ -n "${ES_PASSWORD:-}" ]]; then
  echo "  ES_USERNAME=${ES_USERNAME:-elastic}"
  echo "  ES_PASSWORD=(設定済み)"
fi
echo ""

echo "Registering secrets..."
bash "$ROOT/infra/cloud-build/setup-secrets.sh"

echo ""
echo "Updating Cloud Build trigger substitutions..."
bash "$ROOT/infra/cloud-build/setup-triggers.sh"

echo ""
echo "=== Elasticsearch setup complete ==="
echo ""
echo "Next steps:"
echo "  1. bash infra/elasticsearch/apply-cloud-run.sh   # 即時に Cloud Run へ反映"
echo "  2. bash infra/elasticsearch/sync-production.sh   # 本番 DB → ES reindex + embed"
echo "  3. pnpm --filter @tabipla/backend-api run deploy  # または main マージで自動デプロイ"
echo "  4. pnpm --filter @tabipla/agent run deploy"
