#!/usr/bin/env bash
set -euo pipefail

# スポット画像用 GCS バケットを作成し、Cloud Run からの書き込み・公開読み取りを設定する。
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CREDS_FILE="$ROOT/infra/gcs/.credentials"

PROJECT="${GOOGLE_CLOUD_PROJECT:-$(gcloud config get-value project 2>/dev/null || true)}"
if [[ -z "$PROJECT" || "$PROJECT" == "(unset)" ]]; then
  echo "GOOGLE_CLOUD_PROJECT または gcloud config set project を設定してください" >&2
  exit 1
fi

# 東京リージョン（Cloud Run と同一。GCS 画像バケットも東京推奨）
LOCATION="${GCS_BUCKET_LOCATION:-asia-northeast1}"
BUCKET="${GCS_BUCKET:-${PROJECT}-spot-images}"
OBJECT_PREFIX="${GCS_OBJECT_PREFIX:-spots}"

echo "Project:  ${PROJECT}"
echo "Location: ${LOCATION}"
echo "Bucket:   ${BUCKET}"
echo ""

echo "Enabling Cloud Storage API..."
gcloud services enable storage.googleapis.com --project="$PROJECT" --quiet

if gcloud storage buckets describe "gs://${BUCKET}" --project="$PROJECT" >/dev/null 2>&1; then
  echo "Bucket gs://${BUCKET} already exists."
else
  echo "Creating bucket gs://${BUCKET}..."
  gcloud storage buckets create "gs://${BUCKET}" \
    --project="$PROJECT" \
    --location="$LOCATION" \
    --uniform-bucket-level-access \
    --public-access-prevention=inherited \
    --quiet
fi

echo "Granting public read access (allUsers: objectViewer)..."
gcloud storage buckets add-iam-policy-binding "gs://${BUCKET}" \
  --project="$PROJECT" \
  --member="allUsers" \
  --role="roles/storage.objectViewer" \
  --quiet >/dev/null

PROJECT_NUMBER="$(gcloud projects describe "$PROJECT" --format='value(projectNumber)')"
RUN_SA="${PROJECT_NUMBER}-compute@developer.gserviceaccount.com"

echo "Granting Cloud Run service account write access..."
gcloud storage buckets add-iam-policy-binding "gs://${BUCKET}" \
  --project="$PROJECT" \
  --member="serviceAccount:${RUN_SA}" \
  --role="roles/storage.objectAdmin" \
  --quiet >/dev/null

PUBLIC_BASE_URL="https://storage.googleapis.com/${BUCKET}"

mkdir -p "$(dirname "$CREDS_FILE")"
cat >"$CREDS_FILE" <<EOF
# Generated by infra/gcs/setup.sh — DO NOT COMMIT
PROJECT=${PROJECT}
GCS_BUCKET=${BUCKET}
GCS_BUCKET_LOCATION=${LOCATION}
GCS_OBJECT_PREFIX=${OBJECT_PREFIX}
GCS_PUBLIC_BASE_URL=${PUBLIC_BASE_URL}
EOF
chmod 600 "$CREDS_FILE"

echo ""
echo "=== GCS setup complete ==="
echo ""
echo "Credentials saved to: infra/gcs/.credentials"
echo ""
echo "Public URL pattern:"
echo "  ${PUBLIC_BASE_URL}/${OBJECT_PREFIX}/{spotId}.{ext}"
echo ""
echo "Next steps:"
echo "  1. services/backend-api/.env に GCS_BUCKET=${BUCKET} を追加（または deploy が .credentials を読む）"
echo "  2. pnpm --filter @tabipla/backend-api run deploy"
echo "  3. 管理画面から画像を再アップロード（DB の imageUrl が GCS 直 URL に更新される）"
echo ""
echo "Optional: bash infra/gcs/setup-cdn.sh  # Cloud CDN を有効化"
