#!/usr/bin/env bash
set -euo pipefail

# Cloud SQL (PostgreSQL 16) を tabipla 用に作成し、Cloud Run 接続の IAM を設定する。
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CREDS_FILE="$ROOT/infra/cloud-sql/.credentials"

PROJECT="${GOOGLE_CLOUD_PROJECT:-$(gcloud config get-value project 2>/dev/null || true)}"
if [[ -z "$PROJECT" || "$PROJECT" == "(unset)" ]]; then
  echo "GOOGLE_CLOUD_PROJECT または gcloud config set project を設定してください" >&2
  exit 1
fi

REGION="${GOOGLE_CLOUD_LOCATION:-us-central1}"
INSTANCE="${CLOUD_SQL_INSTANCE_NAME:-tabipla-db}"
DB_NAME="${CLOUD_SQL_DB_NAME:-tabipla}"
DB_USER="${CLOUD_SQL_DB_USER:-tabipla}"
DB_PASSWORD="${CLOUD_SQL_DB_PASSWORD:-$(openssl rand -base64 18 | tr -d '/+=' | head -c 24)}"

echo "Project:  ${PROJECT}"
echo "Region:   ${REGION}"
echo "Instance: ${INSTANCE}"
echo ""

echo "Enabling Cloud SQL Admin API..."
gcloud services enable sqladmin.googleapis.com --project="$PROJECT" --quiet

if gcloud sql instances describe "$INSTANCE" --project="$PROJECT" >/dev/null 2>&1; then
  echo "Cloud SQL instance '${INSTANCE}' already exists."
else
  echo "Creating Cloud SQL instance '${INSTANCE}' (POSTGRES_16, db-f1-micro)..."
  echo "This may take 5–10 minutes."
  gcloud sql instances create "$INSTANCE" \
    --project="$PROJECT" \
    --database-version=POSTGRES_16 \
    --edition=enterprise \
    --tier=db-f1-micro \
    --region="$REGION" \
    --storage-type=SSD \
    --storage-size=10GB \
    --storage-auto-increase \
    --backup-start-time=03:00 \
    --availability-type=zonal \
    --root-password="$DB_PASSWORD" \
    --quiet
fi

if gcloud sql databases describe "$DB_NAME" --instance="$INSTANCE" --project="$PROJECT" >/dev/null 2>&1; then
  echo "Database '${DB_NAME}' already exists."
else
  echo "Creating database '${DB_NAME}'..."
  gcloud sql databases create "$DB_NAME" \
    --instance="$INSTANCE" \
    --project="$PROJECT" \
    --quiet
fi

echo "Setting password for user '${DB_USER}'..."
gcloud sql users create "$DB_USER" \
  --instance="$INSTANCE" \
  --project="$PROJECT" \
  --password="$DB_PASSWORD" \
  --quiet 2>/dev/null \
  || gcloud sql users set-password "$DB_USER" \
    --instance="$INSTANCE" \
    --project="$PROJECT" \
    --password="$DB_PASSWORD" \
    --quiet

CONNECTION_NAME="$(gcloud sql instances describe "$INSTANCE" \
  --project="$PROJECT" \
  --format='value(connectionName)')"
PROJECT_NUMBER="$(gcloud projects describe "$PROJECT" --format='value(projectNumber)')"
RUN_SA="${PROJECT_NUMBER}-compute@developer.gserviceaccount.com"

echo "Granting roles/cloudsql.client to Cloud Run service account..."
gcloud projects add-iam-policy-binding "$PROJECT" \
  --member="serviceAccount:${RUN_SA}" \
  --role="roles/cloudsql.client" \
  --quiet >/dev/null

ENCODED_PASSWORD="$(python3 -c "import urllib.parse; print(urllib.parse.quote('''${DB_PASSWORD}''', safe=''))")"
DATABASE_URL_CLOUD_RUN="postgresql://${DB_USER}:${ENCODED_PASSWORD}@/${DB_NAME}?host=/cloudsql/${CONNECTION_NAME}"
DATABASE_URL_LOCAL="postgresql://${DB_USER}:${ENCODED_PASSWORD}@127.0.0.1:5434/${DB_NAME}"

mkdir -p "$(dirname "$CREDS_FILE")"
cat >"$CREDS_FILE" <<EOF
# Generated by infra/cloud-sql/setup.sh — DO NOT COMMIT
PROJECT=${PROJECT}
REGION=${REGION}
INSTANCE=${INSTANCE}
CONNECTION_NAME=${CONNECTION_NAME}
DB_NAME=${DB_NAME}
DB_USER=${DB_USER}
DB_PASSWORD=${DB_PASSWORD}
CLOUD_SQL_INSTANCE=${CONNECTION_NAME}
DATABASE_URL_CLOUD_RUN=${DATABASE_URL_CLOUD_RUN}
DATABASE_URL_LOCAL=${DATABASE_URL_LOCAL}
EOF
chmod 600 "$CREDS_FILE"

echo ""
echo "=== Cloud SQL setup complete ==="
echo ""
echo "Credentials saved to: infra/cloud-sql/.credentials"
echo ""
echo "Cloud Run / backend-api deploy 用 DATABASE_URL:"
echo "  ${DATABASE_URL_CLOUD_RUN}"
echo ""
echo "ローカル（Cloud SQL Auth Proxy 5434 番）:"
echo "  ${DATABASE_URL_LOCAL}"
echo ""
echo "Next steps:"
echo "  1. services/backend-api/.env の DATABASE_URL を上記 Cloud Run 用に更新"
echo "  2. bash infra/cloud-sql/migrate.sh   # マイグレーション"
echo "  3. pnpm --filter @tabipla/backend-api run deploy"
